import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import { Sidebar } from "lucide-react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="tr">
      <body className="bg-background text-foreground min-h-screen">
        <Navbar />
        <div className="flex">
          <Sidebar />
          <main className="flex-1 p-4 ml-64 bg-muted min-h-screen overflow-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}